title: "Panopticon"
encoding: UTF-8
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
collections:
  document:
    output: true
  secure:
    output: true
exclude:
  - LICENSE
  - README.md
  - node_modules/*
  - package-lock.json
  - package.json
  - server.js
  - build.js
  - clues.json